### ISSUE TITLE
grep results in listing all file

### ISSUE THREAD

**Issue by ericvhileman** [magesec/magesec#58]
[root@web ~]# wget https://magesec.org/download/grep-standard.txt
--2017-03-16 02:18:21--  https://magesec.org/download/grep-standard.txt
Resolving magesec.org... 199.189.226.236
Connecting to magesec.org|199.189.226.236|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14382 (14K) [text/plain]
Saving to: “grep-standard.txt”

100%[==========================================================>] 14,382      --.-K/s   in 0s

2017-03-16 02:18:21 (210 MB/s) - “grep-standard.txt” saved [14382/14382]

[root@web ~]# grep -Erlf grep-standard.txt /home/dev/public_html/magento
/home/dev/public_html/magento/rebill.php
/home/dev/public_html/magento/get.php
/home/dev/public_html/magento/.gitattributes
/home/dev/public_html/magento/maghashes.txt
/home/dev/public_html/magento/.htaccess
/home/dev/public_html/magento/RELEASE_NOTES.txt
/home/dev/public_html/magento/api.php
/home/dev/public_html/magento/.htaccess.sample
/home/dev/public_html/magento/favicon.png
/home/dev/public_html/magento/downloader/template/index.phtml
/home/dev/public_html/magento/downloader/template/.htaccess
/home/dev/public_html/magento/downloader/template/exception.phtml
/home/dev/public_html/magento/downloader/template/settings.phtml
/home/dev/public_html/magento/downloader/template/install/download.phtml
/home/dev/public_html/magento/downloader/template/install/footer.phtml
/home/dev/public_html/magento/downloader/template/install/writable.phtml
/home/dev/public_html/magento/downloader/template/install/header.phtml
/home/dev/public_html/magento/downloader/template/footer.phtml
/home/dev/public_html/magento/downloader/template/writable.phtml
/home/dev/public_html/magento/downloader/template/noroute.phtml
/home/dev/public_html/magento/downloader/template/connect/packages.phtml.orig
/home/dev/public_html/magento/downloader/template/connect/iframe.phtml
/home/dev/public_html/magento/downloader/template/connect/packages_prepare.phtml
/home/dev/public_html/magento/downloader/template/connect/packages.phtml
/home/dev/public_html/magento/downloader/template/messages.phtml
/home/dev/public_html/magento/downloader/template/header.phtml
/home/dev/public_html/magento/downloader/template/login.phtml
/home/dev/public_html/magento/downloader/.cache/community/Lib_Js_Ext-1.7.0.0.tgz
/home/dev/public_html/magento/downloader/.cache/community/Mage_All_Latest-1.7.0.0.tgz
/home/dev/public_html/magento/downloader/.cache/community/Mage_Centinel-1.7.0.0.tgz
/home/dev/public_html/magento/downloader/.cache/community/Lib_Varien-1.7.0.0.tgz
/home/dev/public_html/magento/downloader/.cache/community/Interface_Frontend_Base_Default-1.7.0.0.tgz
/home/dev/public_html/magento/downloader/.cache/community/Lib_LinLibertineFont-2.8.14.1.tgz

**Comment by ericvhileman** [comment]
The problem appears to be https://magesec.org/download/grep-standard.txt does not escape |'s.  If you use -F it will work.  Escaping the |'s and using with -E works.

**Comment by gnuzealot** [comment]
Fixed in #55
