### ISSUE TITLE
--ruleset magesec download throws SNIMissingWarning 

### ISSUE THREAD

**Issue by ericvhileman** [magesec/magesec#60]
[root@hilemanmhm ~]# mwscan --ruleset magesec /home/eric/public_html
[*] Using Magesec rules.
[*] Fetching yara-standard.yar
/usr/lib/python2.6/site-packages/requests/packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/lib/python2.6/site-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
[*] Fetching whitelist.json
/usr/lib/python2.6/site-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
[*] Loaded 259 yara rules and 114763 whitelist entries
[*] Finished scanning 87753 files: 0 malware and 607 whitelisted.
[root@hilemanmhm ~]#

**Comment by gwillem** [comment]
Fixed in https://github.com/gwillem/magento-malware-scanner/pull/68
