### ISSUE TITLE
Older libyara doesn't support "hash"

### ISSUE THREAD

**Issue by gwillem** [magesec/magesec#64]
On CentOS 6:

```
$ mwscan -s magesec /tmp
[*] Using Magesec rules.
[*] Fetching yara-standard.yar
[*] Fetching whitelist.json
yara.SyntaxError: unknown module "hash"
```
This can be fixed by upgrading Yara. However, our Yara rules don't even use the hash module, so we'd better not import it at all.

**Comment by gnuzealot** [comment]
removed from the generation code in #55 will need to rebuild rules once merged
